# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='craig',
            old_name='Craig_city',
            new_name='city',
        ),
    ]
